"""Project Planck SMICA HEALPix into a Mollweide-grid CSV.

Requirements:
    pip install healpy numpy astropy

The output CSV schema matches /scripts/simulate/cmb_map.ts, so the
React component (src/modules/cosmology/plots/CMBMap.tsx) reads either
file interchangeably.

Inputs:
    COM_CMB_IQU-smica_2048_R3.00_full.fits  (~600 MB, Planck Legacy Archive)

Outputs:
    /public/data/cmb_mollweide.csv

Columns:
    x       — Mollweide x in [-2, 2]
    y       — Mollweide y in [-1, 1]
    t_uk    — temperature anomaly in microkelvin

Only points inside the Mollweide ellipse (x/2)^2 + y^2 <= 1 are emitted.

Run from repo root:
    python scripts/fetch/cmb_map_to_csv.py path/to/smica.fits
"""

from __future__ import annotations

import argparse
from pathlib import Path

import healpy as hp
import numpy as np

GRID_W = 720
GRID_H = 360
DOWNSAMPLE_NSIDE = 256  # ~800k HEALPix pixels, plenty for a 720x360 display grid


def mollweide_inverse(x: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Standard Mollweide inverse on the (-2..2) by (-1..1) ellipse.

    Returns (lon, lat, mask) where lon ∈ [-π, π], lat ∈ [-π/2, π/2],
    mask is True for points inside the ellipse.
    """
    mask = (x * x) / 4.0 + y * y <= 1.0
    theta = np.arcsin(np.clip(y, -1.0, 1.0))
    lat = np.arcsin((2 * theta + np.sin(2 * theta)) / np.pi)
    with np.errstate(divide="ignore", invalid="ignore"):
        lon = (np.pi * x) / (2.0 * np.cos(theta))
    mask &= np.abs(lon) <= np.pi
    return lon, lat, mask


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "fits_path",
        type=Path,
        help="Path to COM_CMB_IQU-smica_2048_R3.00_full.fits",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("public/data/cmb_mollweide.csv"),
        help="Output CSV path (default: public/data/cmb_mollweide.csv)",
    )
    args = parser.parse_args()

    print(f"Reading {args.fits_path} …")
    # Planck SMICA: column 0 is the temperature in K.
    m_kelvin = hp.read_map(str(args.fits_path), field=0, dtype=np.float32)
    print(f"  loaded Nside={hp.get_nside(m_kelvin)} ({m_kelvin.size} pixels)")

    if hp.get_nside(m_kelvin) > DOWNSAMPLE_NSIDE:
        print(f"  downsampling to Nside={DOWNSAMPLE_NSIDE}")
        m_kelvin = hp.ud_grade(m_kelvin, DOWNSAMPLE_NSIDE)

    # Convert to microkelvin anomaly (subtract monopole).
    m_uk = (m_kelvin - np.mean(m_kelvin)) * 1.0e6

    # Build the Mollweide grid and invert.
    xs = np.linspace(-2.0, 2.0, GRID_W)
    ys = np.linspace(-1.0, 1.0, GRID_H)
    xx, yy = np.meshgrid(xs, ys)
    lon, lat, mask = mollweide_inverse(xx, yy)

    # HEALPix convention: theta = π/2 − lat (colatitude), phi = lon.
    theta_hp = np.pi / 2.0 - lat[mask]
    phi_hp = lon[mask]
    sampled = hp.get_interp_val(m_uk, theta_hp, phi_hp)

    x_flat = xx[mask]
    y_flat = yy[mask]

    print(f"  emitting {x_flat.size} interior points")

    header_lines = [
        "# REAL DATA, Planck 2018 SMICA temperature map (foreground-cleaned)",
        f"# Generated by: /scripts/fetch/cmb_map_to_csv.py  (Nside={DOWNSAMPLE_NSIDE})",
        "# To regenerate: download SMICA FITS from Planck Legacy Archive, see cmb_map.md",
        "# Real source: Planck 2018 results IV, A&A 641, A4",
        "# Schema: x (Mollweide, -2..2), y (Mollweide, -1..1), t_uk (microkelvin)",
        f"# Grid: {GRID_W}x{GRID_H} Mollweide cells, {x_flat.size} interior points",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as f:
        f.write("\n".join(header_lines) + "\n")
        f.write("x,y,t_uk\n")
        for x, y, t in zip(x_flat, y_flat, sampled):
            f.write(f"{x:.4f},{y:.4f},{t:.2f}\n")

    print(f"Wrote {args.out} ({x_flat.size} pixels, {GRID_W}x{GRID_H} grid)")


if __name__ == "__main__":
    main()
