"""Convert the EHT M87* image into a Mosaic-friendly (x, y, intensity) CSV.

Input: a JPEG of the published M87* image (the iconic 2019 ring), as
distributed by the EHT collaboration and mirrored by ESO. The script
accepts the high-resolution ESO JPG and produces a small CSV that the
React component loads into DuckDB and renders via vg.raster.

The script can also accept a FITS file (if one is available locally),
in which case the angular scale is read from the WCS headers instead
of being assumed from the press-release crop.

Requirements:
    pip install Pillow numpy astropy

Inputs:
    eso1907a.jpg               public press-release JPG (7416 x 4320 RGB)
                               from https://cdn.eso.org/images/large/eso1907a.jpg
    OR
    m87_image_*.fits           an EHT 2019 image FITS (with WCS)

Outputs:
    /public/data/eht_m87.csv

Columns:
    x_uas       — angular x offset in microarcseconds, centered on source
    y_uas       — angular y offset in microarcseconds
    intensity   — normalized image brightness in [0, 1]

Run from repo root:
    python scripts/fetch/eht_m87_to_csv.py /tmp/eso_eht_m87.jpg
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from PIL import Image

GRID_N = 200
PRESS_RELEASE_FOV_UAS = 100.0


def from_eso_jpg(path: Path) -> np.ndarray:
    """Crop ESO press-release JPG to a centered square and downsample to GRID_N."""
    im = Image.open(path).convert("RGB")
    w, h = im.size
    side = min(w, h)
    left = (w - side) // 2
    top = (h - side) // 2
    im = im.crop((left, top, left + side, top + side))
    im = im.resize((GRID_N, GRID_N), Image.LANCZOS)
    rgb = np.asarray(im, dtype=np.float32) / 255.0
    intensity = rgb.max(axis=2)
    intensity = np.clip(intensity, 0.0, 1.0)
    return intensity


def from_fits(path: Path) -> tuple[np.ndarray, float]:
    """Read a 2D FITS image, return the array and total FoV in μas from WCS."""
    from astropy.io import fits

    with fits.open(path) as hdul:
        hdu = next((h for h in hdul if h.data is not None), None)
        if hdu is None:
            raise RuntimeError(f"No image extension found in {path}")
        data = hdu.data.astype(np.float32)
        while data.ndim > 2:
            data = data[0]
        cdelt1 = abs(hdu.header.get("CDELT1", hdu.header.get("CD1_1", 0.0)))
        if cdelt1 == 0:
            fov_uas = PRESS_RELEASE_FOV_UAS
        else:
            radians_per_pixel = abs(cdelt1) * (np.pi / 180.0)
            uas_per_pixel = radians_per_pixel * 206264.806 * 1e6
            fov_uas = uas_per_pixel * data.shape[-1]

    finite = data[np.isfinite(data)]
    if finite.size == 0:
        raise RuntimeError("FITS image has no finite pixels")
    intensity = (data - finite.min()) / (finite.max() - finite.min() + 1e-30)
    intensity = np.clip(intensity, 0.0, 1.0).astype(np.float32)

    if intensity.shape != (GRID_N, GRID_N):
        im = Image.fromarray((intensity * 255).astype(np.uint8))
        side = min(im.size)
        left = (im.size[0] - side) // 2
        top = (im.size[1] - side) // 2
        im = im.crop((left, top, left + side, top + side)).resize(
            (GRID_N, GRID_N), Image.LANCZOS
        )
        intensity = np.asarray(im, dtype=np.float32) / 255.0

    return intensity, fov_uas


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "image_path",
        type=Path,
        help="Path to eso1907a.jpg (or an EHT M87 image FITS).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("public/data/eht_m87.csv"),
        help="Output CSV path (default: public/data/eht_m87.csv)",
    )
    parser.add_argument(
        "--fov-uas",
        type=float,
        default=PRESS_RELEASE_FOV_UAS,
        help=f"Field of view in microarcseconds (default {PRESS_RELEASE_FOV_UAS}).",
    )
    args = parser.parse_args()

    print(f"Reading {args.image_path} …")
    suffix = args.image_path.suffix.lower()
    fov_uas = args.fov_uas
    if suffix in {".fits", ".fit"}:
        intensity, fov_uas = from_fits(args.image_path)
        source_kind = "REAL DATA, EHT 2019 M87* FITS"
    else:
        intensity = from_eso_jpg(args.image_path)
        source_kind = "REAL DATA, EHT 2019 M87* image (ESO press release)"

    print(f"  grid {intensity.shape[0]}x{intensity.shape[1]}, FoV {fov_uas:.1f} μas")

    xs = np.linspace(-fov_uas / 2, fov_uas / 2, GRID_N)
    ys = np.linspace(fov_uas / 2, -fov_uas / 2, GRID_N)
    xx, yy = np.meshgrid(xs, ys)

    header_lines = [
        f"# {source_kind}",
        "# Generated by: /scripts/fetch/eht_m87_to_csv.py",
        "# To regenerate: see /scripts/fetch/eht_m87.md",
        "# Real source: EHT Collaboration et al. (2019) ApJL 875, L1; ESO release eso1907a",
        f"# Schema: x_uas, y_uas, intensity (normalized, 0..1). FoV {fov_uas:.1f} μas",
        f"# Grid: {GRID_N}x{GRID_N} cells, {GRID_N * GRID_N} pixels",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as f:
        f.write("\n".join(header_lines) + "\n")
        f.write("x_uas,y_uas,intensity\n")
        for j in range(GRID_N):
            for i in range(GRID_N):
                v = float(intensity[j, i])
                if v > 0.005:
                    f.write(f"{xx[j, i]:.3f},{yy[j, i]:.3f},{v:.4f}\n")

    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
