// Simulate a BOSS DR12-like binned correlation function ξ(s).
//
// Physics: the fiducial model in /src/physics/bao.ts evaluated at the
// fiducial sound horizon r_d ≈ 147.78 Mpc, with Gaussian scatter
// matched to the BOSS DR12 published error bars.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  SOUND_HORIZON_FIDUCIAL_MPC,
  approximateBossSigma,
  baoCorrelation,
} from "../../src/modules/cosmology/physics/bao.js";
import { gaussian, mulberry32 } from "../../src/lib/rng.js";

const S_MIN = 50;
const S_MAX = 200;
const N_BINS = 30;
const SEED = 1234;

function generate(): string[] {
  const rng = mulberry32(SEED);
  const rows: string[] = [];
  const step = (S_MAX - S_MIN) / N_BINS;
  for (let i = 0; i < N_BINS; i++) {
    const s = S_MIN + step * (i + 0.5);
    const xiTrue = baoCorrelation(s, SOUND_HORIZON_FIDUCIAL_MPC);
    const sigma = approximateBossSigma(s, xiTrue);
    const xiObs = xiTrue + gaussian(rng, 0, sigma);
    rows.push(
      `${s.toFixed(2)},${xiObs.toExponential(4)},${(xiObs - sigma).toExponential(4)},${(xiObs + sigma).toExponential(4)},${sigma.toExponential(4)}`,
    );
  }
  return rows;
}

function main(): void {
  const header = [
    "# SIMULATED DATA, not real BOSS measurements",
    "# Generated by: /scripts/simulate/bao.ts",
    "# To replace with real data: see /scripts/fetch/bao.md",
    "# Real source: BOSS DR12, Alam et al. (2017) MNRAS 470, 2617",
    "# Schema: s_mpc (separation Mpc), xi (correlation), xi_lower, xi_upper, sigma",
    `# Fiducial: r_d = ${SOUND_HORIZON_FIDUCIAL_MPC} Mpc; seed=${SEED}, N_bins=${N_BINS}`,
  ];
  const body = ["s_mpc,xi,xi_lower,xi_upper,sigma", ...generate()];
  const text = [...header, ...body].join("\n") + "\n";
  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(here, "..", "..", "public", "data", "boss_xi.csv");
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, text, "utf8");
  console.log(`Wrote ${outPath} (${N_BINS} bins, s ∈ [${S_MIN}, ${S_MAX}] Mpc)`);
}

main();
