// Theory grid + observed values for BBN.
//
// The "simulate" name is slight: the curves are real model predictions
// from /src/physics/bbn.ts (PArthENoPE/Cyburt analytical fits), and the
// observed values are real published measurements (Cooke 2018, Aver
// 2015, Sbordone 2010). The CSV-and-header pipeline is shared with
// truly-simulated datasets for consistency.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  BBN_OBSERVED,
  N_EFF_STANDARD,
  bbnGrid,
} from "../../src/modules/cosmology/physics/bbn.js";

const N_SAMPLES = 80;

function writeGrid(outDir: string): void {
  const grid = bbnGrid(N_EFF_STANDARD, {
    omegaBh2Min: 0.005,
    omegaBh2Max: 0.05,
    samples: N_SAMPLES,
  });
  const header = [
    "# REAL DATA (theory grid from analytical fits), not measured",
    "# Generated by: /scripts/simulate/bbn.ts",
    "# To replace with PArthENoPE-grade grid: see /scripts/fetch/bbn.md",
    "# Real source: Cyburt et al. (2016) Rev. Mod. Phys. 88, 015004",
    "# Schema: omega_bh2 (dimensionless), dH (D/H), yp (Y_p), li7H (⁷Li/H)",
    `# Grid: N_eff = ${N_EFF_STANDARD}, log-uniform Ω_b h² in [0.005, 0.05], ${N_SAMPLES} samples`,
  ];
  const rows = grid.map(
    (r) =>
      `${r.omegaBh2.toFixed(5)},${r.dH.toExponential(4)},${r.yp.toFixed(5)},${r.li7H.toExponential(4)}`,
  );
  const text = [...header, "omega_bh2,dH,yp,li7H", ...rows].join("\n") + "\n";
  writeFileSync(resolve(outDir, "bbn_grid.csv"), text, "utf8");
}

function writeObserved(outDir: string): void {
  const header = [
    "# REAL DATA, observed primordial abundances",
    "# Generated by: /scripts/simulate/bbn.ts (transcribed from cited papers)",
    "# To replace with newer measurements: see /scripts/fetch/bbn.md",
    "# Real source: Cooke 2018 (D/H), Aver 2015 (Y_p), Sbordone 2010 (⁷Li/H)",
    "# Schema: species (string), value, sigma (1σ uncertainty), source (paper)",
    "# Values: D/H = (2.527 ± 0.030)e-5, Y_p = 0.2449 ± 0.0040, ⁷Li/H = (1.6 ± 0.3)e-10",
  ];
  const rows = [
    `D/H,${BBN_OBSERVED.dH.value.toExponential(4)},${BBN_OBSERVED.dH.sigma.toExponential(4)},${BBN_OBSERVED.dH.source}`,
    `Y_p,${BBN_OBSERVED.yp.value.toFixed(5)},${BBN_OBSERVED.yp.sigma.toFixed(5)},${BBN_OBSERVED.yp.source}`,
    `Li7/H,${BBN_OBSERVED.li7H.value.toExponential(4)},${BBN_OBSERVED.li7H.sigma.toExponential(4)},${BBN_OBSERVED.li7H.source}`,
  ];
  const text = [...header, "species,value,sigma,source", ...rows].join("\n") + "\n";
  writeFileSync(resolve(outDir, "bbn_observed.csv"), text, "utf8");
}

function main(): void {
  const here = dirname(fileURLToPath(import.meta.url));
  const outDir = resolve(here, "..", "..", "public", "data");
  mkdirSync(outDir, { recursive: true });
  writeGrid(outDir);
  writeObserved(outDir);
  console.log(`Wrote bbn_grid.csv (${N_SAMPLES} samples) and bbn_observed.csv`);
}

main();
