// CMB temperature field on a Mollweide (x, y) grid.
//
// Output schema is the same whether the pipeline is fed by the
// JS procedural fallback in src/modules/cosmology/physics/cmbMap.ts
// (this script) or by real Planck SMICA HEALPix data via the Python
// pipeline in /scripts/fetch/cmb_map_to_csv.py.
//
// Columns:
//   x       — Mollweide x in [-2, 2]
//   y       — Mollweide y in [-1, 1]
//   t_uk    — temperature anomaly in microkelvin
//
// Only points inside the Mollweide ellipse (x/2)^2 + y^2 <= 1 are emitted.
//
// Coordinates match the standard Mollweide projection (semi-major 2 by
// semi-minor 1 ellipse). For each (x, y) inside the ellipse we invert
// to (lon, lat) and sample the temperature field at that direction.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { mulberry32 } from "../../src/lib/rng.js";

const GRID_W = 720;
const GRID_H = 360;
const SEED = 42;
const SPECKLE_AMP_UK = 60;

interface Blob {
  lon: number;
  lat: number;
  sigma: number;
  amp: number;
}

function makeBlobs(rng: () => number, n: number): Blob[] {
  const out: Blob[] = [];
  for (let i = 0; i < n; i++) {
    out.push({
      lon: (rng() * 2 - 1) * Math.PI,
      lat: (rng() - 0.5) * Math.PI * 0.9,
      sigma: 0.3 + rng() * 0.5,
      amp: (rng() - 0.5) * 250,
    });
  }
  return out;
}

function lowFrequencyAt(lon: number, lat: number, blobs: Blob[]): number {
  let t = 0;
  for (const b of blobs) {
    const dLon = Math.atan2(Math.sin(lon - b.lon), Math.cos(lon - b.lon));
    const dLat = lat - b.lat;
    const r2 = (dLon * dLon + dLat * dLat) / (b.sigma * b.sigma);
    t += b.amp * Math.exp(-r2);
  }
  return t;
}

function speckleField(
  rng: () => number,
  width: number,
  height: number,
  amp: number,
): Float32Array {
  const raw = new Float32Array(width * height);
  for (let i = 0; i < raw.length; i++) {
    let u = 0;
    let v = 0;
    while (u === 0) u = rng();
    while (v === 0) v = rng();
    raw[i] = amp * Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
  }
  const out = new Float32Array(width * height);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      let sum = 0;
      let count = 0;
      for (let dy = -2; dy <= 2; dy++) {
        for (let dx = -2; dx <= 2; dx++) {
          const xi = x + dx;
          const yi = y + dy;
          if (xi >= 0 && xi < width && yi >= 0 && yi < height) {
            sum += raw[yi * width + xi]!;
            count++;
          }
        }
      }
      out[y * width + x] = sum / count;
    }
  }
  return out;
}

function mollweideInverseProper(
  x: number,
  y: number,
): { lon: number; lat: number } | null {
  if (y < -1 || y > 1) return null;
  if ((x * x) / 4 + y * y > 1) return null;
  const theta = Math.asin(y);
  const lat = Math.asin((2 * theta + Math.sin(2 * theta)) / Math.PI);
  const lon = (Math.PI * x) / (2 * Math.cos(theta));
  if (lon < -Math.PI || lon > Math.PI) return null;
  return { lon, lat };
}

function main(): void {
  const rng = mulberry32(SEED);
  const blobs = makeBlobs(rng, 12);
  const speckle = speckleField(
    mulberry32(SEED + 1),
    GRID_W,
    GRID_H,
    SPECKLE_AMP_UK,
  );

  const rows: string[] = [];
  for (let j = 0; j < GRID_H; j++) {
    const y = (j / (GRID_H - 1)) * 2 - 1;
    for (let i = 0; i < GRID_W; i++) {
      const x = ((i / (GRID_W - 1)) * 2 - 1) * 2;
      const lonlat = mollweideInverseProper(x, y);
      if (!lonlat) continue;
      const t = lowFrequencyAt(lonlat.lon, lonlat.lat, blobs) + speckle[j * GRID_W + i]!;
      rows.push(`${x.toFixed(4)},${y.toFixed(4)},${t.toFixed(2)}`);
    }
  }

  const header = [
    "# SIMULATED DATA, procedural CMB-like field (NOT real Planck data)",
    "# Generated by: /scripts/simulate/cmb_map.ts",
    "# To replace with real Planck SMICA: see /scripts/fetch/cmb_map.md",
    "# Real source: Planck 2018 results IV, A&A 641, A4",
    "# Schema: x (Mollweide, -2..2), y (Mollweide, -1..1), t_uk (microkelvin)",
    `# Grid: ${GRID_W}x${GRID_H} Mollweide cells, ${rows.length} interior points`,
  ];
  const text = [...header, "x,y,t_uk", ...rows].join("\n") + "\n";

  const here = dirname(fileURLToPath(import.meta.url));
  const outDir = resolve(here, "..", "..", "public", "data");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(resolve(outDir, "cmb_mollweide.csv"), text, "utf8");
  console.log(
    `Wrote cmb_mollweide.csv (${rows.length} pixels, ${GRID_W}x${GRID_H} grid)`,
  );
}

main();
