// Simulate Planck-like binned TT power spectrum D_ℓ.
//
// Physics: the fiducial spectrum is the analytical model in
// /src/physics/cmb.ts, evaluated at Planck 2018 best-fit cosmology.
// Each bin gets Gaussian scatter drawn with σ from approximatePlanckSigma,
// which combines cosmic-variance (~Dℓ * √(2/(2ℓ+1)Δℓ f_sky)) with a
// Planck-like noise rise in the damping tail.
//
// Output schema: ell,Dl,Dl_lower,Dl_upper,sigma — pre-computed
// lower/upper bounds make the Mosaic error-bar rule trivial to render.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  PLANCK_2018,
  approximatePlanckSigma,
  cmbModelDl,
} from "../../src/physics/cmb.js";
import { gaussian, mulberry32 } from "../../src/physics/rng.js";

const ELL_MIN = 30; // below ℓ=30, low-ℓ likelihood uses different binning
const ELL_MAX = 2500;
const N_BINS = 45;
const BIN_WIDTH = (ELL_MAX - ELL_MIN) / N_BINS;
const SEED = 2024;

// Mostly-linear bin centers; finer at low ℓ where the SW plateau lives.
function binCenters(): number[] {
  const centers: number[] = [];
  for (let i = 0; i < N_BINS; i++) {
    centers.push(ELL_MIN + BIN_WIDTH * (i + 0.5));
  }
  return centers;
}

function generate(): string[] {
  const rng = mulberry32(SEED);
  const ells = binCenters();
  const fiducial = cmbModelDl(ells, PLANCK_2018);
  const rows: string[] = [];
  for (let i = 0; i < ells.length; i++) {
    const ell = ells[i]!;
    const dlTrue = fiducial[i]!;
    const sigma = approximatePlanckSigma(ell, dlTrue, BIN_WIDTH);
    const dlObs = Math.max(0, dlTrue + gaussian(rng, 0, sigma));
    const lower = dlObs - sigma;
    const upper = dlObs + sigma;
    rows.push(
      [
        ell.toFixed(1),
        dlObs.toFixed(2),
        lower.toFixed(2),
        upper.toFixed(2),
        sigma.toFixed(2),
      ].join(","),
    );
  }
  return rows;
}

function main(): void {
  const header = [
    "# SIMULATED DATA — not real Planck measurements",
    "# Generated by: /scripts/simulate/cmb_powerspectrum.ts",
    "# To replace with real data: see /scripts/fetch/cmb_powerspectrum.md",
    "# Real source: Planck 2018, Planck Collab. (2020) A&A 641, A6",
    "# Schema: ell (multipole), Dl (μK²), Dl_lower (Dl-σ), Dl_upper (Dl+σ), sigma (μK²)",
    `# Fiducial: ΛCDM (H0=${PLANCK_2018.H0}, Ω_m=${PLANCK_2018.omegaM}, Ω_bh²=${PLANCK_2018.omegaBh2}, n_s=${PLANCK_2018.nS}); seed=${SEED}, N_bins=${N_BINS}`,
  ];
  const body = ["ell,Dl,Dl_lower,Dl_upper,sigma", ...generate()];
  const text = [...header, ...body].join("\n") + "\n";

  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(here, "..", "..", "public", "data", "planck_dl.csv");
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, text, "utf8");
  console.log(`Wrote ${outPath} (${N_BINS} bins, ℓ ∈ [${ELL_MIN}, ${ELL_MAX}])`);
}

main();
