// Simulate the GW150914 strain time series.
//
// We generate ~0.45 s of strain h(t) sampled at 2048 Hz then
// downsample to 512 Hz for shipping. The inspiral chirp from
// /src/physics/chirp.ts is added to Gaussian detector noise scaled to
// the published LIGO H1 sensitivity (~10⁻²² strain RMS over the
// ~50-300 Hz band). The merger is at t ≈ 0.42 s.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  GW150914_FIDUCIAL,
  chirpWaveform,
} from "../../src/modules/cosmology/physics/chirp.js";
import { gaussian, mulberry32 } from "../../src/lib/rng.js";

const SAMPLE_RATE_HZ = 2048;
const DURATION_S = 0.45;
const SEED = 150914;
const NOISE_RMS = 1.5e-22;
const DOWNSAMPLE_FACTOR = 4;

function generate(): { t: number; h: number; h_model: number }[] {
  const rng = mulberry32(SEED);
  const n = Math.floor(SAMPLE_RATE_HZ * DURATION_S);
  const ts: number[] = [];
  for (let i = 0; i < n; i++) ts.push(i / SAMPLE_RATE_HZ);
  const hModel = chirpWaveform(ts, GW150914_FIDUCIAL.tc, GW150914_FIDUCIAL.chirpMassSolar);
  return ts.map((t, i) => ({
    t,
    h_model: hModel[i]!,
    h: hModel[i]! + gaussian(rng, 0, NOISE_RMS),
  }));
}

function main(): void {
  const rows = generate();
  const downsampled = rows.filter((_, i) => i % DOWNSAMPLE_FACTOR === 0);
  const header = [
    "# SIMULATED DATA, not real LIGO strain",
    "# Generated by: /scripts/simulate/gw150914.ts",
    "# To replace with real GWOSC strain: see /scripts/fetch/gw150914.md",
    "# Real source: GW150914, Abbott et al. (LIGO 2016) PRL 116, 061102",
    "# Schema: t_s (seconds), strain (× 10⁻²¹), strain_model (× 10⁻²¹)",
    `# Fiducial M_c = ${GW150914_FIDUCIAL.chirpMassSolar} M_☉; sample_rate = ${SAMPLE_RATE_HZ / DOWNSAMPLE_FACTOR} Hz; noise_rms = ${NOISE_RMS}`,
  ];
  const body = downsampled.map(
    (r) =>
      `${r.t.toFixed(5)},${(r.h * 1e21).toFixed(4)},${(r.h_model * 1e21).toFixed(4)}`,
  );
  const text = [...header, "t_s,strain,strain_model", ...body].join("\n") + "\n";
  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(here, "..", "..", "public", "data", "gw150914_strain.csv");
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, text, "utf8");
  console.log(`Wrote ${outPath} (${downsampled.length} samples, ${DURATION_S}s)`);
}

main();
