// Simulate the 24-galaxy Hubble 1929 sample.
//
// Physics: v = H0 * d. Hubble's 1929 best-fit slope was H0 ≈ 500 km/s/Mpc
// (an order of magnitude high, his distance ladder was miscalibrated by
// a factor of ~7 due to Cepheid type confusion). We use that value here
// because the goal is to reproduce the SHAPE of Hubble's original scatter
// plot, not the modern value. The scatter at fixed distance reflects the
// real peculiar-velocity scatter of nearby galaxies (~150-250 km/s).
//
// Output schema: name,distance_mpc,velocity_km_s, same column names a
// "real" fetched table would use, so the loader doesn't care which source
// produced the file.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { hubbleVelocity } from "../../src/physics/friedmann.js";
import { gaussian, mulberry32 } from "../../src/physics/rng.js";

const HUBBLE_1929_SLOPE_KM_S_PER_MPC = 500;
const DISTANCE_MIN_MPC = 0.03;
const DISTANCE_MAX_MPC = 2.0;
const N_GALAXIES = 24;
const PECULIAR_VELOCITY_SIGMA_KM_S = 200;
const SEED = 42;

function logUniform(rng: () => number, lo: number, hi: number): number {
  const logLo = Math.log(lo);
  const logHi = Math.log(hi);
  return Math.exp(logLo + (logHi - logLo) * rng());
}

function fakeName(i: number): string {
  return `SIM-${String(i + 1).padStart(3, "0")}`;
}

function generate(): string[] {
  const rng = mulberry32(SEED);
  const rows: string[] = [];
  for (let i = 0; i < N_GALAXIES; i++) {
    const d = logUniform(rng, DISTANCE_MIN_MPC, DISTANCE_MAX_MPC);
    const vTrue = hubbleVelocity(d, HUBBLE_1929_SLOPE_KM_S_PER_MPC);
    const vObs = vTrue + gaussian(rng, 0, PECULIAR_VELOCITY_SIGMA_KM_S);
    rows.push(`${fakeName(i)},${d.toFixed(4)},${vObs.toFixed(1)}`);
  }
  return rows;
}

function main(): void {
  const header = [
    "# SIMULATED DATA, not real measurements",
    "# Generated by: /scripts/simulate/hubble1929.ts",
    "# To replace with real data: see /scripts/fetch/hubble1929.md",
    "# Real source: Hubble 1929 PNAS, doi:10.1073/pnas.15.3.168",
    "# Schema: name (string), distance_mpc (Mpc), velocity_km_s (km/s)",
    `# Generated H0 = ${HUBBLE_1929_SLOPE_KM_S_PER_MPC} km/s/Mpc, σ_peculiar = ${PECULIAR_VELOCITY_SIGMA_KM_S} km/s, seed = ${SEED}`,
  ];
  const body = ["name,distance_mpc,velocity_km_s", ...generate()];
  const text = [...header, ...body].join("\n") + "\n";

  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(here, "..", "..", "public", "data", "hubble1929.csv");
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, text, "utf8");
  console.log(`Wrote ${outPath}`);
}

main();
