// Simulate a Pantheon+-like sample of Type Ia supernovae.
//
// Physics: μ(z) computed from /src/physics/luminosity.ts at the
// fiducial ΛCDM cosmology (H0=70, Ω_m=0.3, Ω_Λ=0.7). Each simulated SN
// is drawn at a redshift sampled from a Pantheon+-like distribution
// (heavily peaked at z ~ 0.05-0.2, long tail to z ~ 2) and given σ_μ
// that grows roughly as 0.1 + 0.15·z (typical Pantheon+ uncertainties).

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { distanceModulus } from "../../src/modules/cosmology/physics/luminosity.js";
import { gaussian, mulberry32 } from "../../src/lib/rng.js";

const FIDUCIAL = { H0: 70, omegaM: 0.3, omegaLambda: 0.7 };
const N_SN = 250;
const SEED = 17;

function sampleRedshift(rng: () => number): number {
  const u = rng();
  return 0.005 + 2.2 * Math.pow(u, 2.3);
}

function generate(): string[] {
  const rng = mulberry32(SEED);
  const rows: string[] = [];
  for (let i = 0; i < N_SN; i++) {
    const z = sampleRedshift(rng);
    const muTrue = distanceModulus(z, FIDUCIAL);
    const sigma = 0.10 + 0.15 * z + 0.05 * gaussian(rng, 0, 1) ** 2;
    const muObs = muTrue + gaussian(rng, 0, sigma);
    rows.push(`${z.toFixed(4)},${muObs.toFixed(3)},${sigma.toFixed(3)}`);
  }
  rows.sort((a, b) => parseFloat(a.split(",")[0]!) - parseFloat(b.split(",")[0]!));
  return rows;
}

function main(): void {
  const header = [
    "# SIMULATED DATA, not real Pantheon+ measurements",
    "# Generated by: /scripts/simulate/pantheon.ts",
    "# To replace with real data: see /scripts/fetch/pantheon.md",
    "# Real source: Pantheon+ (Brout et al. 2022) ApJ 938, 110",
    "# Schema: z (redshift), mu (distance modulus, mag), sigma (1σ μ uncertainty)",
    `# Fiducial: H0=70, Ω_m=0.3, Ω_Λ=0.7; seed=${SEED}, N_sn=${N_SN}`,
  ];
  const body = ["z,mu,sigma", ...generate()];
  const text = [...header, ...body].join("\n") + "\n";
  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(here, "..", "..", "public", "data", "pantheon_plus.csv");
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, text, "utf8");
  console.log(`Wrote ${outPath} (${N_SN} simulated SNe)`);
}

main();
