// Simulate 3 SPARC-like rotation curves: a dwarf, a Milky Way analogue,
// and a giant spiral. Each is sampled at ~12-18 radial points with a
// realistic v_obs scatter and a separate v_baryonic-only column.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  baryonEnclosedMass,
  circularVelocityKmS,
  nfwEnclosedMass,
} from "../../src/modules/cosmology/physics/nfw.js";
import { gaussian, mulberry32 } from "../../src/lib/rng.js";

interface GalaxySpec {
  name: string;
  diskMassSolar: number;
  scaleKpc: number;
  rsKpc: number;
  rhoSMsunPerKpc3: number;
  rMinKpc: number;
  rMaxKpc: number;
  nPoints: number;
}

const GALAXIES: GalaxySpec[] = [
  { name: "NGC 3198", diskMassSolar: 3e10, scaleKpc: 2.6, rsKpc: 10, rhoSMsunPerKpc3: 9e6, rMinKpc: 1, rMaxKpc: 30, nPoints: 14 },
  { name: "DDO 154", diskMassSolar: 2.5e8, scaleKpc: 0.8, rsKpc: 3.5, rhoSMsunPerKpc3: 8e6, rMinKpc: 0.5, rMaxKpc: 8, nPoints: 12 },
  { name: "UGC 2885", diskMassSolar: 1.5e11, scaleKpc: 6, rsKpc: 24, rhoSMsunPerKpc3: 6e6, rMinKpc: 2, rMaxKpc: 60, nPoints: 16 },
];

const SEED = 31415;
const SIGMA_FRAC = 0.04;

function generate(): string[] {
  const rng = mulberry32(SEED);
  const rows: string[] = [];
  for (const g of GALAXIES) {
    for (let i = 0; i < g.nPoints; i++) {
      const t = i / (g.nPoints - 1);
      const r = g.rMinKpc + (g.rMaxKpc - g.rMinKpc) * t;
      const mBary = baryonEnclosedMass(r, g.diskMassSolar, g.scaleKpc);
      const mDm = nfwEnclosedMass(r, { rsKpc: g.rsKpc, rhoSMsunPerKpc3: g.rhoSMsunPerKpc3 });
      const vBary = circularVelocityKmS(r, mBary);
      const vTotTrue = circularVelocityKmS(r, mBary + mDm);
      const sigma = Math.max(2, SIGMA_FRAC * vTotTrue);
      const vObs = vTotTrue + gaussian(rng, 0, sigma);
      rows.push(
        `${g.name},${r.toFixed(2)},${vObs.toFixed(2)},${sigma.toFixed(2)},${vBary.toFixed(2)}`,
      );
    }
  }
  return rows;
}

function main(): void {
  const header = [
    "# SIMULATED DATA, not real SPARC measurements",
    "# Generated by: /scripts/simulate/sparc.ts",
    "# To replace with real data: see /scripts/fetch/sparc.md",
    "# Real source: SPARC, Lelli, McGaugh, Schombert (2016) AJ 152, 157",
    "# Schema: name, r_kpc, v_kms, sigma_kms, v_baryonic_kms",
    `# Generated for 3 galaxies (NGC 3198, DDO 154, UGC 2885); seed=${SEED}`,
  ];
  const body = ["name,r_kpc,v_kms,sigma_kms,v_baryonic_kms", ...generate()];
  const text = [...header, ...body].join("\n") + "\n";
  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(here, "..", "..", "public", "data", "sparc_galaxies.csv");
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, text, "utf8");
  console.log(`Wrote ${outPath}`);
}

main();
